name: wifi_complaint
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  get: 4.6.5
  fluttertoast: 8.1.1
  url_launcher: 6.1.6
  flutter_screenutil: 5.6.0
  cloud_firestore: 4.0.5
  firebase_core: 2.2.0
  random_string: 2.3.1
  firebase_auth: 4.1.2
  geolocator: 9.0.2
  map_launcher: 2.4.0
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  
flutter_icons: 
  android: launcher_icon
  image_path: assets/images/ic_launcher.png
  ios: true
  min_sdk_android: 23

flutter: 
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true

