name: wifi_complaint
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluttertoast: 8.1.1
  url_launcher: 6.1.6
  flutter_screenutil: 5.6.0
  get_storage: 2.0.3
  cloud_firestore: 4.0.5
  firebase_core: 2.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

